CREATE OR REPLACE FUNCTION public.get_crm_report(p_from timestamptz, p_to timestamptz)
RETURNS jsonb LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path = public AS $$
DECLARE v_hub uuid := public.get_my_hub_id(); v_previous_from timestamptz := p_from - (p_to-p_from); v_result jsonb; BEGIN
  IF NOT public.can_manage_crm() THEN RAISE EXCEPTION 'CRM access required'; END IF;
  SELECT jsonb_build_object(
    'new_leads',count(*) FILTER(WHERE created_at>=p_from AND created_at<p_to),
    'cohort_conversions',count(*) FILTER(WHERE created_at>=p_from AND created_at<p_to AND converted_at IS NOT NULL),
    'conversions_completed',count(*) FILTER(WHERE converted_at>=p_from AND converted_at<p_to),
    'conversion_rate',CASE WHEN count(*) FILTER(WHERE created_at>=p_from AND created_at<p_to)=0 THEN 0 ELSE round(100.0*count(*) FILTER(WHERE created_at>=p_from AND created_at<p_to AND converted_at IS NOT NULL)/count(*) FILTER(WHERE created_at>=p_from AND created_at<p_to),1) END,
    'previous_new_leads',count(*) FILTER(WHERE created_at>=v_previous_from AND created_at<p_from),
    'previous_conversions',count(*) FILTER(WHERE converted_at>=v_previous_from AND converted_at<p_from),
    'cold',count(*) FILTER(WHERE qualification='cold'),'warm',count(*) FILTER(WHERE qualification='warm'),'hot',count(*) FILTER(WHERE qualification='hot'),
    'outstanding_follow_ups',(SELECT count(*) FROM public.lead_follow_ups f WHERE f.hub_id=v_hub AND f.status='pending' AND f.due_at<now()),
    'trend',(SELECT COALESCE(jsonb_agg(jsonb_build_object('date',dates.series_day,'leads',COALESCE(l.total,0),'conversions',COALESCE(c.total,0)) ORDER BY dates.series_day),'[]'::jsonb) FROM generate_series(p_from::date,(p_to-interval '1 day')::date,interval '1 day') AS dates(series_day) LEFT JOIN (SELECT created_at::date AS series_day,count(*) total FROM public.crm_leads WHERE hub_id=v_hub AND created_at>=p_from AND created_at<p_to GROUP BY 1) l ON l.series_day=dates.series_day LEFT JOIN (SELECT converted_at::date AS series_day,count(*) total FROM public.crm_leads WHERE hub_id=v_hub AND converted_at>=p_from AND converted_at<p_to GROUP BY 1) c ON c.series_day=dates.series_day),
    'sources',(SELECT COALESCE(jsonb_agg(jsonb_build_object('name',name,'value',total) ORDER BY total DESC),'[]'::jsonb) FROM (SELECT COALESCE(s.name,'Unknown') name,count(*) total FROM public.crm_leads l LEFT JOIN public.lead_sources s ON s.id=l.source_id WHERE l.hub_id=v_hub AND l.created_at>=p_from AND l.created_at<p_to GROUP BY 1) q),
    'funnel',(SELECT COALESCE(jsonb_agg(jsonb_build_object('name',replace(initcap(lifecycle_status),'_',' '),'key',lifecycle_status,'value',total) ORDER BY array_position(ARRAY['new_lead','contacted','interested','follow_up','registered','not_interested'],lifecycle_status)),'[]'::jsonb) FROM (SELECT lifecycle_status,count(*) total FROM public.crm_leads WHERE hub_id=v_hub AND created_at>=p_from AND created_at<p_to GROUP BY 1) q),
    'qualification',(SELECT COALESCE(jsonb_agg(jsonb_build_object('name',initcap(qualification),'key',qualification,'value',total)),'[]'::jsonb) FROM (SELECT qualification,count(*) total FROM public.crm_leads WHERE hub_id=v_hub GROUP BY 1) q),
    'follow_ups',(SELECT jsonb_build_object('completed',count(*) FILTER(WHERE status='completed'),'cancelled',count(*) FILTER(WHERE status='cancelled'),'overdue',count(*) FILTER(WHERE status='pending' AND due_at<now()),'completion_rate',CASE WHEN count(*) FILTER(WHERE status IN('completed','cancelled'))=0 THEN 0 ELSE round(100.0*count(*) FILTER(WHERE status='completed')/count(*) FILTER(WHERE status IN('completed','cancelled')),1) END,'average_hours',COALESCE(round(avg(extract(epoch FROM(completed_at-created_at))/3600) FILTER(WHERE status='completed'),1),0)) FROM public.lead_follow_ups WHERE hub_id=v_hub AND due_at>=p_from AND due_at<p_to),
    'campaigns',(SELECT jsonb_build_object('sent',count(*) FILTER(WHERE sent_at IS NOT NULL),'delivered',count(*) FILTER(WHERE delivered_at IS NOT NULL),'opened',count(*) FILTER(WHERE opened_at IS NOT NULL),'clicked',count(*) FILTER(WHERE clicked_at IS NOT NULL),'bounced',count(*) FILTER(WHERE bounced_at IS NOT NULL),'open_rate',CASE WHEN count(*) FILTER(WHERE delivered_at IS NOT NULL)=0 THEN 0 ELSE round(100.0*count(*) FILTER(WHERE opened_at IS NOT NULL)/count(*) FILTER(WHERE delivered_at IS NOT NULL),1) END,'click_rate',CASE WHEN count(*) FILTER(WHERE delivered_at IS NOT NULL)=0 THEN 0 ELSE round(100.0*count(*) FILTER(WHERE clicked_at IS NOT NULL)/count(*) FILTER(WHERE delivered_at IS NOT NULL),1) END) FROM public.marketing_email_deliveries WHERE hub_id=v_hub AND created_at>=p_from AND created_at<p_to),
    'owners',(SELECT COALESCE(jsonb_agg(jsonb_build_object('name',name,'leads',leads,'conversions',conversions,'rate',CASE WHEN leads=0 THEN 0 ELSE round(100.0*conversions/leads,1) END) ORDER BY leads DESC),'[]'::jsonb) FROM (SELECT COALESCE(p.full_name,p.email,'Unassigned') name,count(*) leads,count(*) FILTER(WHERE l.converted_at IS NOT NULL) conversions FROM public.crm_leads l LEFT JOIN public.profiles p ON p.user_id=l.owner_id WHERE l.hub_id=v_hub AND l.created_at>=p_from AND l.created_at<p_to GROUP BY 1) q),
    'programs',(SELECT COALESCE(jsonb_agg(jsonb_build_object('name',name,'leads',leads,'conversions',conversions) ORDER BY leads DESC),'[]'::jsonb) FROM (SELECT COALESCE(p.program_name,'Not specified') name,count(*) leads,count(*) FILTER(WHERE l.converted_at IS NOT NULL) conversions FROM public.crm_leads l LEFT JOIN public.programs p ON p.id=l.program_interest_id WHERE l.hub_id=v_hub AND l.created_at>=p_from AND l.created_at<p_to GROUP BY 1) q)
  ) INTO v_result FROM public.crm_leads WHERE hub_id=v_hub;
  RETURN v_result;
END $$;

GRANT EXECUTE ON FUNCTION public.get_crm_report(timestamptz,timestamptz) TO authenticated;
NOTIFY pgrst, 'reload schema';
