// @ts-nocheck
import { useState } from 'react';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { supabase } from '@/lib/supabase';
import { PageHeader } from '@/components/shared/PageHeader';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { Award, Check, Loader2, MessageSquareQuote, RotateCcw, X } from 'lucide-react';
import { toast } from 'sonner';

export default function CompletionManagementPage(){
  const client=useQueryClient(); const [moderating,setModerating]=useState<any>(null); const [notes,setNotes]=useState(''); const [revoke,setRevoke]=useState<any>(null); const [reason,setReason]=useState(''); const [waive,setWaive]=useState<any>(null); const [waiverReason,setWaiverReason]=useState('');
  const {data,isLoading}=useQuery({queryKey:['completion-admin'],queryFn:async()=>{const [t,c,q]=await Promise.all([supabase.from('testimonials').select('*,cohorts(cohort_label,programs(program_name))').order('created_at',{ascending:false}),supabase.from('certificates').select('*').order('created_at',{ascending:false}),supabase.rpc('get_completion_admin_queue')]);if(t.error)throw t.error;if(c.error)throw c.error;if(q.error)throw q.error;const ids=[...new Set((t.data||[]).map((x:any)=>x.student_id))];const p=ids.length?await supabase.from('profiles').select('user_id,full_name,email').in('user_id',ids):{data:[],error:null};if(p.error)throw p.error;const byId=new Map((p.data||[]).map((x:any)=>[x.user_id,x]));return{testimonials:(t.data||[]).map((x:any)=>({...x,profiles:byId.get(x.student_id)||null})),certificates:c.data||[],queue:q.data||[]}}});
  const moderate=async(status:string)=>{try{const{error}=await supabase.rpc('moderate_testimonial',{p_testimonial_id:moderating.id,p_status:status,p_notes:notes||null,p_destinations:[]});if(error)throw error;toast.success('Testimonial updated');setModerating(null);client.invalidateQueries({queryKey:['completion-admin']});}catch(e:any){toast.error(e.message)}};
  const revokeCertificate=async()=>{try{const{error}=await supabase.rpc('revoke_certificate',{p_certificate_id:revoke.id,p_reason:reason});if(error)throw error;toast.success('Certificate revoked');setRevoke(null);client.invalidateQueries({queryKey:['completion-admin']});}catch(e:any){toast.error(e.message)}};
  const reissue=async(id:string)=>{try{const{error}=await supabase.rpc('reissue_certificate',{p_certificate_id:id});if(error)throw error;await supabase.functions.invoke('generate-certificates',{body:{}});toast.success('Replacement certificate queued');client.invalidateQueries({queryKey:['completion-admin']});}catch(e:any){toast.error(e.message)}};
  const grantWaiver=async()=>{try{const{error}=await supabase.rpc('waive_course_feedback',{p_cohort_id:waive.cohort_id,p_student_id:waive.student_id,p_reason:waiverReason});if(error)throw error;await supabase.functions.invoke('generate-certificates',{body:{}});toast.success('Feedback requirement waived');setWaive(null);client.invalidateQueries({queryKey:['completion-admin']});}catch(e:any){toast.error(e.message)}};
  if(isLoading)return <div className="py-20 flex justify-center"><Loader2 className="animate-spin"/></div>;
  return <div><PageHeader title="Completion & Testimonials" description="Moderate learner stories and manage issued certificates."/>
    <Tabs defaultValue="queue" className="mt-6"><TabsList><TabsTrigger value="queue">Completion queue</TabsTrigger><TabsTrigger value="testimonials">Testimonials</TabsTrigger><TabsTrigger value="certificates">Certificates</TabsTrigger></TabsList>
      <TabsContent value="queue" className="mt-4 space-y-3">{data?.queue.map((row:any)=><div key={row.cohort_student_id} className="rounded-xl border p-4 flex flex-col sm:flex-row sm:items-center justify-between gap-3"><div><p className="font-medium">{row.learner_name}</p><p className="text-xs text-muted-foreground">{row.program_name} · {row.cohort_label}</p></div><div className="flex flex-wrap items-center gap-2"><Badge variant={row.feedback_completed?'default':'outline'}>Feedback {row.feedback_completed?'done':'missing'}</Badge><Badge variant={row.testimonial_decision?'default':'outline'}>Testimonial {row.testimonial_decision||'pending'}</Badge><Badge variant={row.certificate_status==='issued'?'default':'outline'}>Certificate {row.certificate_status?.replace('_',' ')||'waiting'}</Badge>{!row.feedback_completed&&<Button size="sm" variant="outline" onClick={()=>{setWaive(row);setWaiverReason('')}}>Waive feedback</Button>}</div></div>)}{!data?.queue.length&&<p className="text-center text-muted-foreground py-12">No graduated learners are awaiting completion.</p>}</TabsContent>
      <TabsContent value="testimonials" className="mt-4 space-y-3">{data?.testimonials.map((t:any)=><div key={t.id} className="rounded-xl border p-5"><div className="flex justify-between gap-3"><div><p className="font-medium">{t.profiles?.full_name||'Learner'}</p><p className="text-xs text-muted-foreground">{t.cohorts?.programs?.program_name} · {t.cohorts?.cohort_label}</p></div><div className="flex gap-2"><Badge variant="outline" className="capitalize">{t.decision}</Badge><Badge className="capitalize">{t.moderation_status.replace('_',' ')}</Badge></div></div>{t.testimonial_text&&<blockquote className="mt-4 rounded-lg bg-muted/40 p-4 text-sm">“{t.testimonial_text}”</blockquote>}<div className="mt-3 flex justify-between items-center"><p className="text-xs text-muted-foreground">{t.publication_consent?'Publication consent granted':'Internal only / no publication consent'}</p>{t.decision==='submitted'&&<Button size="sm" variant="outline" onClick={()=>{setModerating(t);setNotes(t.moderation_notes||'')}}><MessageSquareQuote className="h-4 w-4 mr-1"/>Review</Button>}</div></div>)}{!data?.testimonials.length&&<p className="text-center text-muted-foreground py-12">No testimonial decisions yet.</p>}</TabsContent>
      <TabsContent value="certificates" className="mt-4 space-y-3">{data?.certificates.map((c:any)=><div key={c.id} className="rounded-xl border p-4 flex flex-col sm:flex-row sm:items-center justify-between gap-3"><div><p className="font-medium flex items-center gap-2"><Award className="h-4 w-4 text-primary"/>{c.learner_name}</p><p className="text-xs text-muted-foreground mt-1">{c.certificate_number} · {c.program_name} · v{c.version}</p>{c.generation_error&&<p className="text-xs text-destructive mt-1">{c.generation_error}</p>}</div><div className="flex items-center gap-2"><Badge className="capitalize">{c.status.replace('_',' ')}</Badge>{c.status==='issued'&&<Button size="sm" variant="destructive" onClick={()=>{setRevoke(c);setReason('')}}>Revoke</Button>}{c.status==='revoked'&&<Button size="sm" variant="outline" onClick={()=>reissue(c.id)}><RotateCcw className="h-4 w-4 mr-1"/>Reissue</Button>}</div></div>)}{!data?.certificates.length&&<p className="text-center text-muted-foreground py-12">No certificates yet.</p>}</TabsContent>
    </Tabs>
    <Dialog open={!!moderating} onOpenChange={o=>!o&&setModerating(null)}><DialogContent><DialogHeader><DialogTitle>Moderate testimonial</DialogTitle></DialogHeader><div className="space-y-4"><div><Label>Internal moderation notes</Label><Textarea value={notes} onChange={e=>setNotes(e.target.value)} rows={3}/></div><div className="flex gap-2"><Button variant="destructive" onClick={()=>moderate('rejected')}><X className="h-4 w-4 mr-1"/>Reject</Button><Button variant="outline" onClick={()=>moderate('changes_requested')}>Request changes</Button><Button className="ml-auto" disabled={!moderating?.publication_consent} onClick={()=>moderate('approved')}><Check className="h-4 w-4 mr-1"/>Approve</Button></div>{!moderating?.publication_consent&&<p className="text-xs text-muted-foreground">This learner did not grant publication consent, so the testimonial cannot be approved for public use.</p>}</div></DialogContent></Dialog>
    <Dialog open={!!revoke} onOpenChange={o=>!o&&setRevoke(null)}><DialogContent><DialogHeader><DialogTitle>Revoke certificate</DialogTitle></DialogHeader><div className="space-y-4"><div><Label>Reason</Label><Input value={reason} onChange={e=>setReason(e.target.value)} placeholder="Required for the audit trail"/></div><Button variant="destructive" className="w-full" disabled={reason.trim().length<10} onClick={revokeCertificate}>Revoke certificate</Button></div></DialogContent></Dialog>
    <Dialog open={!!waive} onOpenChange={o=>!o&&setWaive(null)}><DialogContent><DialogHeader><DialogTitle>Waive course feedback</DialogTitle></DialogHeader><div className="space-y-4"><p className="text-sm text-muted-foreground">Use this only when the learner cannot access or complete the feedback form. The reason is recorded in the audit log.</p><div><Label>Reason</Label><Textarea value={waiverReason} onChange={e=>setWaiverReason(e.target.value)} rows={3}/></div><Button className="w-full" disabled={waiverReason.trim().length<10} onClick={grantWaiver}>Record waiver</Button></div></DialogContent></Dialog>
  </div>;
}
