import { useEffect, useState } from 'react';
import { supabase } from '@/lib/supabase';
import { PageHeader } from '@/components/shared/PageHeader';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Badge } from '@/components/ui/badge';
import { toast } from 'sonner';
import { Megaphone } from 'lucide-react';

export default function CrmCampaignsPage() {
  const [campaigns, setCampaigns] = useState<any[]>([]); const [form, setForm] = useState({ name: '', subject: '', html_body: '', qualification: 'all', delay_hours: '0' });
  const load = async () => { const { data } = await (supabase.from('marketing_campaigns' as any) as any).select('*,marketing_campaign_steps(id)').order('created_at', { ascending: false }); setCampaigns(data || []); };
  useEffect(() => { load(); }, []);
  const create = async () => { if (!form.name || !form.subject || !form.html_body) return toast.error('Name, subject, and content are required'); const template = await (supabase.from('marketing_email_templates' as any) as any).insert({ name: `${form.name} – step 1`, subject: form.subject, html_body: form.html_body }).select().single(); if (template.error) return toast.error(template.error.message); const campaign = await (supabase.from('marketing_campaigns' as any) as any).insert({ name: form.name, entry_rules: form.qualification === 'all' ? {} : { qualification: [form.qualification] } }).select().single(); if (campaign.error) return toast.error(campaign.error.message); const step = await (supabase.from('marketing_campaign_steps' as any) as any).insert({ campaign_id: campaign.data.id, template_id: template.data.id, step_order: 1, delay_hours: Number(form.delay_hours) }); if (step.error) return toast.error(step.error.message); toast.success('Campaign draft created'); setForm({ name: '', subject: '', html_body: '', qualification: 'all', delay_hours: '0' }); load(); };
  const status = async (campaign: any, next: string) => { const result = next === 'active' ? await (supabase.rpc as any)('activate_marketing_campaign', { p_campaign_id: campaign.id }) : await (supabase.from('marketing_campaigns' as any) as any).update({ status: next }).eq('id', campaign.id); result.error ? toast.error(result.error.message) : (toast.success(`Campaign ${next}`), load()); };
  return <div><PageHeader title="Campaigns" description="Consent-based automated email sequences" /><div className="grid gap-6 xl:grid-cols-[minmax(0,1.2fr)_minmax(360px,0.8fr)]"><Card><CardHeader><CardTitle>Create campaign</CardTitle></CardHeader><CardContent className="space-y-4"><div><Label>Name</Label><Input value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} /></div><div><Label>Entry qualification</Label><Select value={form.qualification} onValueChange={qualification => setForm({ ...form, qualification })}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{['all','cold','warm','hot'].map(x => <SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select></div><div><Label>First step delay (hours)</Label><Input type="number" min="0" value={form.delay_hours} onChange={e => setForm({ ...form, delay_hours: e.target.value })} /></div><div><Label>Subject</Label><Input value={form.subject} onChange={e => setForm({ ...form, subject: e.target.value })} placeholder="Hello {{name}}" /></div><div><Label>HTML content</Label><Textarea rows={8} value={form.html_body} onChange={e => setForm({ ...form, html_body: e.target.value })} /><p className="text-xs text-muted-foreground mt-1">Placeholders: name, source, owner, program, hub</p></div><Button onClick={create}>Create draft</Button></CardContent></Card><div className="space-y-3">{campaigns.length === 0 ? <Card className="h-full min-h-72"><CardContent className="h-full flex flex-col items-center justify-center px-8 py-12 text-center"><div className="mb-4 rounded-full bg-primary/10 p-4"><Megaphone className="h-7 w-7 text-primary" /></div><h2 className="font-heading text-lg font-semibold">No campaigns yet</h2><p className="mt-2 max-w-sm text-sm text-muted-foreground">Create your first draft using the form. It will appear here, ready for review and activation.</p></CardContent></Card> : campaigns.map(c => <Card key={c.id}><CardContent className="pt-6 flex items-center justify-between gap-4"><div><p className="font-semibold">{c.name}</p><p className="text-xs text-muted-foreground">{c.marketing_campaign_steps?.length || 0} step(s)</p></div><div className="flex items-center gap-2"><Badge variant="outline" className="capitalize">{c.status}</Badge>{c.status !== 'active' && <Button size="sm" onClick={() => status(c, 'active')}>Activate</Button>}{c.status === 'active' && <Button size="sm" variant="outline" onClick={() => status(c, 'paused')}>Pause</Button>}</div></CardContent></Card>)}</div></div></div>;
}
