/* eslint-disable @typescript-eslint/no-explicit-any */
import { useEffect, useState } from 'react';
import { useNavigate, useSearchParams } from 'react-router-dom';
import { supabase } from '@/lib/supabase';
import { useAuth } from '@/hooks/useAuth';
import { PageHeader } from '@/components/shared/PageHeader';
import { StatCard } from '@/components/shared/StatCard';
import { DataTable } from '@/components/shared/DataTable';
import { Card, CardContent } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from '@/components/ui/dialog';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { toast } from 'sonner';
import { CalendarCheck, CalendarClock, CheckCircle2, Clock, ExternalLink, MessageCircle, Plus, RotateCcw, XCircle } from 'lucide-react';

export default function CrmFollowUpsPage() {
  const navigate = useNavigate(); const { user } = useAuth(); const [params, setParams] = useSearchParams();
  const [rows, setRows] = useState<any[]>([]); const [leads, setLeads] = useState<any[]>([]); const [owners, setOwners] = useState<any[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const [createOpen, setCreateOpen] = useState(false); const [completeTask, setCompleteTask] = useState<any>(null); const [rescheduleTask, setRescheduleTask] = useState<any>(null);
  const [createForm, setCreateForm] = useState({ lead_id: '', owner_id: user?.id || '', title: 'Lead follow-up', due_at: '', notes: '' }); const [outcome, setOutcome] = useState(''); const [nextDue, setNextDue] = useState(''); const [rescheduleAt, setRescheduleAt] = useState('');
  const view = params.get('view') || 'pending'; const owner = params.get('owner') || 'all';
  const setFilter = (key: string, value: string) => { const next = new URLSearchParams(params); if (value === 'all' || (key === 'view' && value === 'pending')) next.delete(key); else next.set(key, value); setParams(next, { replace: true }); };
  const load = async () => { setLoading(true); setError(''); const [tasks, leadRows, ownerRows] = await Promise.all([(supabase.from('lead_follow_ups' as any) as any).select('*,crm_leads(full_name,email,phone,qualification)').order('due_at'), (supabase.from('crm_leads' as any) as any).select('id,full_name,email').not('lifecycle_status','eq','registered').order('full_name'), (supabase.rpc as any)('list_crm_owners')]); if (tasks.error) setError(tasks.error.message); setRows(tasks.data || []); setLeads(leadRows.data || []); setOwners(ownerRows.data || []); setLoading(false); };
  useEffect(() => { load(); }, []);
  const todayStart = new Date(); todayStart.setHours(0,0,0,0); const tomorrow = new Date(todayStart); tomorrow.setDate(tomorrow.getDate()+1); const dayAfter = new Date(tomorrow); dayAfter.setDate(dayAfter.getDate()+1);
  const pending = rows.filter(x => x.status === 'pending'); const overdue = pending.filter(x => new Date(x.due_at) < new Date()); const today = pending.filter(x => new Date(x.due_at) >= todayStart && new Date(x.due_at) < tomorrow); const upcoming = pending.filter(x => new Date(x.due_at) >= tomorrow);
  const filtered = rows.filter(x => {
    const due = new Date(x.due_at); const matchesView = view === 'all' || (view === 'overdue' ? x.status === 'pending' && due < new Date() : view === 'today' ? x.status === 'pending' && due >= todayStart && due < tomorrow : view === 'upcoming' ? x.status === 'pending' && due >= tomorrow : x.status === view);
    return matchesView && (owner === 'all' || (owner === 'mine' ? x.owner_id === user?.id : x.owner_id === owner));
  });
  const dueLabel = (iso: string) => { const due = new Date(iso); const hours = Math.round(Math.abs(due.getTime()-Date.now())/3600000); if (due < new Date()) return hours < 24 ? `${hours}h overdue` : `${Math.floor(hours/24)}d overdue`; if (due < tomorrow) return 'Today'; if (due < dayAfter) return 'Tomorrow'; return due.toLocaleDateString(); };
  const create = async () => { if (!createForm.lead_id || !createForm.owner_id || !createForm.due_at) return toast.error('Lead, owner, and due date are required'); const due = new Date(createForm.due_at).toISOString(); const { error } = await (supabase.from('lead_follow_ups' as any) as any).insert({ ...createForm, due_at: due }); if (error) return toast.error(error.message); await (supabase.from('crm_leads' as any) as any).update({ next_follow_up_at: due, lifecycle_status: 'follow_up' }).eq('id', createForm.lead_id); toast.success('Follow-up scheduled'); setCreateOpen(false); setCreateForm({ lead_id: '', owner_id: user?.id || '', title: 'Lead follow-up', due_at: '', notes: '' }); load(); };
  const complete = async () => { const { error } = await (supabase.rpc as any)('complete_lead_follow_up', { p_follow_up_id: completeTask.id, p_outcome: outcome || null, p_next_due_at: nextDue ? new Date(nextDue).toISOString() : null }); if (error) return toast.error(error.message); toast.success('Follow-up completed'); setCompleteTask(null); setOutcome(''); setNextDue(''); load(); };
  const cancel = async (task: any) => { const { error } = await (supabase.from('lead_follow_ups' as any) as any).update({ status: 'cancelled', updated_at: new Date().toISOString() }).eq('id', task.id); if (error) return toast.error(error.message); toast.success('Follow-up cancelled'); load(); };
  const reschedule = async () => { if (!rescheduleAt) return; const { error } = await (supabase.from('lead_follow_ups' as any) as any).update({ due_at: new Date(rescheduleAt).toISOString(), reminder_sent_at: null, updated_at: new Date().toISOString() }).eq('id', rescheduleTask.id); if (error) return toast.error(error.message); toast.success('Follow-up rescheduled'); setRescheduleTask(null); setRescheduleAt(''); load(); };
  const columns = [{ key: 'lead', header: 'Lead', render: (r: any) => <div><p className="font-medium">{r.crm_leads?.full_name}</p><p className="text-xs text-muted-foreground">{r.crm_leads?.phone || r.crm_leads?.email}</p></div> }, { key: 'title', header: 'Task', render: (r: any) => <div><p>{r.title}</p>{r.notes && <p className="max-w-xs truncate text-xs text-muted-foreground">{r.notes}</p>}</div> }, { key: 'due_at', header: 'Due', render: (r: any) => <div><p>{new Date(r.due_at).toLocaleString()}</p><p className={`text-xs ${r.status === 'pending' && new Date(r.due_at) < new Date() ? 'font-medium text-destructive' : 'text-muted-foreground'}`}>{dueLabel(r.due_at)}</p></div> }, { key: 'status', header: 'Status', render: (r: any) => <Badge variant="outline" className={r.status === 'pending' && new Date(r.due_at) < new Date() ? 'border-destructive/30 text-destructive' : ''}>{r.status === 'pending' && new Date(r.due_at) < new Date() ? 'overdue' : r.status}</Badge> }, { key: 'actions', header: '', render: (r: any) => <div className="flex gap-1" onClick={e => e.stopPropagation()}>{r.status === 'pending' && <><Button size="sm" onClick={() => setCompleteTask(r)}>Complete</Button><Button size="icon" variant="ghost" onClick={() => { setRescheduleTask(r); setRescheduleAt(new Date(r.due_at).toISOString().slice(0,16)); }}><RotateCcw className="h-4 w-4" /></Button><Button size="icon" variant="ghost" onClick={() => cancel(r)}><XCircle className="h-4 w-4" /></Button></>}<Button size="icon" variant="ghost" onClick={() => navigate(`/admin/crm/leads/${r.lead_id}`)}><ExternalLink className="h-4 w-4" /></Button>{r.crm_leads?.phone && <Button size="icon" variant="ghost" asChild><a href={`https://wa.me/${String(r.crm_leads.phone).replace(/\D/g,'')}`} target="_blank" rel="noreferrer"><MessageCircle className="h-4 w-4" /></a></Button>}</div> }];
  return <div><PageHeader title="Follow-ups" description="Upcoming and overdue lead actions" actions={<Dialog open={createOpen} onOpenChange={setCreateOpen}><DialogTrigger asChild><Button><Plus className="h-4 w-4 mr-2" />Create follow-up</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>Schedule follow-up</DialogTitle></DialogHeader><div className="space-y-4"><div><Label>Lead</Label><Select value={createForm.lead_id} onValueChange={lead_id => setCreateForm({...createForm,lead_id})}><SelectTrigger><SelectValue placeholder="Select lead" /></SelectTrigger><SelectContent>{leads.map(x => <SelectItem key={x.id} value={x.id}>{x.full_name} · {x.email}</SelectItem>)}</SelectContent></Select></div><div><Label>Owner</Label><Select value={createForm.owner_id} onValueChange={owner_id => setCreateForm({...createForm,owner_id})}><SelectTrigger><SelectValue placeholder="Select owner" /></SelectTrigger><SelectContent>{owners.map(x => <SelectItem key={x.user_id} value={x.user_id}>{x.full_name || x.email}</SelectItem>)}</SelectContent></Select></div><div><Label>Task</Label><Input value={createForm.title} onChange={e => setCreateForm({...createForm,title:e.target.value})} /></div><div><Label>Due</Label><Input type="datetime-local" value={createForm.due_at} onChange={e => setCreateForm({...createForm,due_at:e.target.value})} /></div><div><Label>Notes</Label><Textarea value={createForm.notes} onChange={e => setCreateForm({...createForm,notes:e.target.value})} /></div><Button className="w-full" onClick={create}>Schedule</Button></div></DialogContent></Dialog>} />
    <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4 mb-6"><StatCard title="Overdue" value={overdue.length} icon={CalendarClock} /><StatCard title="Due Today" value={today.length} icon={Clock} /><StatCard title="Upcoming" value={upcoming.length} icon={CalendarCheck} /><StatCard title="Completed" value={rows.filter(x => x.status === 'completed').length} icon={CheckCircle2} /></div>
    <div className="flex flex-wrap gap-2 mb-5">{[['pending','Pending'],['overdue','Overdue'],['today','Today'],['upcoming','Upcoming'],['completed','Completed'],['all','All']].map(([value,label]) => <Button key={value} size="sm" variant={view === value ? 'default' : 'outline'} onClick={() => setFilter('view',value)}>{label}</Button>)}<Select value={owner} onValueChange={v => setFilter('owner',v)}><SelectTrigger className="ml-auto w-44"><SelectValue placeholder="All owners" /></SelectTrigger><SelectContent><SelectItem value="all">All owners</SelectItem><SelectItem value="mine">My follow-ups</SelectItem>{owners.map(x => <SelectItem key={x.user_id} value={x.user_id}>{x.full_name || x.email}</SelectItem>)}</SelectContent></Select></div>
    {error ? <Card><CardContent className="py-12 text-center text-destructive">{error}<div><Button variant="outline" className="mt-4" onClick={load}>Try again</Button></div></CardContent></Card> : loading ? <Card><CardContent className="py-16 text-center text-muted-foreground">Loading follow-ups…</CardContent></Card> : rows.length === 0 ? <Card><CardContent className="py-16 text-center"><CalendarClock className="h-10 w-10 text-primary mx-auto mb-4" /><h2 className="font-heading text-lg font-semibold">No follow-ups scheduled</h2><p className="text-sm text-muted-foreground mt-2 mb-5">Schedule a task here or from a lead’s profile.</p><Button onClick={() => setCreateOpen(true)}><Plus className="h-4 w-4 mr-2" />Create follow-up</Button></CardContent></Card> : <DataTable columns={columns} data={filtered} searchable exportable exportFilename="lead-follow-ups" emptyMessage="No follow-ups match this view" onRowClick={r => navigate(`/admin/crm/leads/${r.lead_id}`)} />}
    <Dialog open={!!completeTask} onOpenChange={open => !open && setCompleteTask(null)}><DialogContent><DialogHeader><DialogTitle>Complete follow-up</DialogTitle></DialogHeader><div className="space-y-4"><div><Label>Outcome or note</Label><Textarea value={outcome} onChange={e => setOutcome(e.target.value)} placeholder="What happened?" /></div><div><Label>Schedule next follow-up (optional)</Label><Input type="datetime-local" value={nextDue} onChange={e => setNextDue(e.target.value)} /></div><Button className="w-full" onClick={complete}>Complete follow-up</Button></div></DialogContent></Dialog>
    <Dialog open={!!rescheduleTask} onOpenChange={open => !open && setRescheduleTask(null)}><DialogContent><DialogHeader><DialogTitle>Reschedule follow-up</DialogTitle></DialogHeader><div className="space-y-4"><Input type="datetime-local" value={rescheduleAt} onChange={e => setRescheduleAt(e.target.value)} /><Button className="w-full" onClick={reschedule}>Save new time</Button></div></DialogContent></Dialog>
  </div>;
}
