/* eslint-disable @typescript-eslint/no-explicit-any */
import { useCallback, useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { supabase } from '@/lib/supabase';
import { PageHeader } from '@/components/shared/PageHeader';
import { StatCard } from '@/components/shared/StatCard';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Input } from '@/components/ui/input';
import { AlertCircle, CalendarDays, Clock, Download, Flame, MousePointerClick, Percent, Send, Snowflake, Sun, UserCheck, Users } from 'lucide-react';
import { Bar, BarChart, CartesianGrid, Cell, Legend, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';

const COLORS = ['#4f46e5','#f59e0b','#ef4444','#10b981','#0ea5e9','#8b5cf6'];
const percentChange = (current: number, previous: number) => previous ? `${current >= previous ? '+' : ''}${Math.round((current-previous)*100/previous)}% vs previous period` : current ? 'New in this period' : 'No change';

export default function CrmReportsPage() {
  const navigate = useNavigate(); const now = new Date();
  const [from,setFrom]=useState(new Date(now.getFullYear(),now.getMonth(),1).toISOString().slice(0,10)); const [to,setTo]=useState(new Date(now.getTime()+86400000).toISOString().slice(0,10)); const [report,setReport]=useState<any>({}); const [loading,setLoading]=useState(true); const [error,setError]=useState('');
  const load=useCallback(async()=>{setLoading(true);setError('');const result=await(supabase.rpc as any)('get_crm_report',{p_from:new Date(from).toISOString(),p_to:new Date(to).toISOString()});if(result.error)setError(result.error.message);setReport(result.data||{});setLoading(false);},[from,to]); useEffect(()=>{load();},[load]);
  const preset=(days:number)=>{const end=new Date();end.setDate(end.getDate()+1);const start=new Date();start.setDate(start.getDate()-days+1);setFrom(start.toISOString().slice(0,10));setTo(end.toISOString().slice(0,10));};
  const exportReport=()=>{const rows=[['Metric','Value'],['New leads',report.new_leads||0],['Cohort conversions',report.cohort_conversions||0],['Conversions completed',report.conversions_completed||0],['Cohort conversion rate',`${report.conversion_rate||0}%`],['Overdue follow-ups',report.outstanding_follow_ups||0],['Emails sent',report.campaigns?.sent||0],['Open rate',`${report.campaigns?.open_rate||0}%`],['Click rate',`${report.campaigns?.click_rate||0}%`]];const blob=new Blob([rows.map(r=>r.join(',')).join('\n')],{type:'text/csv'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`crm-report-${from}-${to}.csv`;a.click();URL.revokeObjectURL(url);};
  if(error)return <div><PageHeader title="CRM Reports" description="Lead acquisition, qualification, conversion, and follow-up performance"/><Card className="border-destructive/30"><CardContent className="py-16 text-center"><AlertCircle className="h-9 w-9 text-destructive mx-auto mb-3"/><p className="font-medium">Unable to load CRM reports</p><p className="text-sm text-muted-foreground mt-1">{error}</p><Button variant="outline" className="mt-4" onClick={load}>Try again</Button></CardContent></Card></div>;
  return <div><PageHeader title="CRM Reports" description="Lead acquisition, qualification, conversion, and follow-up performance" actions={<Button variant="outline" onClick={exportReport}><Download className="h-4 w-4 mr-2"/>Export report</Button>}/><div className="flex flex-wrap gap-2 mb-6"><Button size="sm" variant="outline" onClick={()=>preset(7)}>Last 7 days</Button><Button size="sm" variant="outline" onClick={()=>preset(30)}>Last 30 days</Button><Button size="sm" variant="outline" onClick={()=>{setFrom(new Date(now.getFullYear(),now.getMonth(),1).toISOString().slice(0,10));setTo(new Date(now.getTime()+86400000).toISOString().slice(0,10));}}>This month</Button><Input type="date" value={from} onChange={e=>setFrom(e.target.value)} className="w-44"/><Input type="date" value={to} onChange={e=>setTo(e.target.value)} className="w-44"/></div>
    {loading?<Card><CardContent className="py-20 text-center text-muted-foreground">Loading report…</CardContent></Card>:<><div className="grid sm:grid-cols-2 xl:grid-cols-4 gap-4 mb-6"><StatCard title="New leads" value={report.new_leads||0} icon={Users} trend={percentChange(report.new_leads||0,report.previous_new_leads||0)} trendUp={(report.new_leads||0)>=(report.previous_new_leads||0)}/><StatCard title="Conversions completed" value={report.conversions_completed||0} icon={UserCheck} trend={percentChange(report.conversions_completed||0,report.previous_conversions||0)} trendUp={(report.conversions_completed||0)>=(report.previous_conversions||0)}/><StatCard title="Lead cohort conversion rate" value={`${report.conversion_rate||0}%`} icon={Percent}/><StatCard title="Overdue follow-ups" value={report.outstanding_follow_ups||0} icon={Clock}/></div>
    <div className="grid xl:grid-cols-2 gap-6 mb-6"><Card><CardHeader><CardTitle>Acquisition and conversion trend</CardTitle></CardHeader><CardContent className="h-80"><ResponsiveContainer width="100%" height="100%"><LineChart data={report.trend||[]}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="date" tickFormatter={v=>new Date(v).toLocaleDateString(undefined,{month:'short',day:'numeric'})}/><YAxis allowDecimals={false}/><Tooltip/><Legend/><Line type="monotone" dataKey="leads" stroke="#4f46e5" strokeWidth={2}/><Line type="monotone" dataKey="conversions" stroke="#10b981" strokeWidth={2}/></LineChart></ResponsiveContainer></CardContent></Card><Card><CardHeader><CardTitle>Lead sources</CardTitle></CardHeader><CardContent className="h-80"><ResponsiveContainer width="100%" height="100%"><BarChart data={report.sources||[]} layout="vertical" onClick={(e:any)=>e?.activeLabel&&navigate(`/admin/crm/leads?source=${encodeURIComponent(e.activeLabel)}`)}><CartesianGrid strokeDasharray="3 3"/><XAxis type="number" allowDecimals={false}/><YAxis dataKey="name" type="category" width={90}/><Tooltip/><Bar dataKey="value" fill="#4f46e5" radius={[0,4,4,0]}/></BarChart></ResponsiveContainer></CardContent></Card></div>
    <div className="grid xl:grid-cols-2 gap-6 mb-6"><Card><CardHeader><CardTitle>Lead lifecycle funnel</CardTitle></CardHeader><CardContent className="h-80"><ResponsiveContainer width="100%" height="100%"><BarChart data={report.funnel||[]} onClick={(e:any)=>{const item=(report.funnel||[]).find((x:any)=>x.name===e?.activeLabel);if(item)navigate(`/admin/crm/leads?status=${item.key}`);}}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="name"/><YAxis allowDecimals={false}/><Tooltip/><Bar dataKey="value" fill="#8b5cf6" radius={[4,4,0,0]}/></BarChart></ResponsiveContainer></CardContent></Card><Card><CardHeader><CardTitle>Current qualification snapshot</CardTitle></CardHeader><CardContent className="h-80"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={report.qualification||[]} dataKey="value" nameKey="name" innerRadius={60} outerRadius={100} onClick={(item:any)=>navigate(`/admin/crm/leads?qualification=${item.key}`)}>{(report.qualification||[]).map((_:any,i:number)=><Cell key={i} fill={COLORS[i%COLORS.length]}/>)}</Pie><Tooltip/><Legend/></PieChart></ResponsiveContainer></CardContent></Card></div>
    <div className="grid sm:grid-cols-2 xl:grid-cols-4 gap-4 mb-6"><StatCard title="Follow-ups completed" value={report.follow_ups?.completed||0} icon={CalendarDays}/><StatCard title="Follow-up completion rate" value={`${report.follow_ups?.completion_rate||0}%`} icon={UserCheck}/><StatCard title="Average completion time" value={`${report.follow_ups?.average_hours||0}h`} icon={Clock}/><StatCard title="Follow-ups overdue" value={report.follow_ups?.overdue||0} icon={AlertCircle}/></div>
    <div className="grid sm:grid-cols-2 xl:grid-cols-5 gap-4 mb-6"><StatCard title="Emails sent" value={report.campaigns?.sent||0} icon={Send}/><StatCard title="Delivered" value={report.campaigns?.delivered||0} icon={UserCheck}/><StatCard title="Open rate" value={`${report.campaigns?.open_rate||0}%`} icon={Percent}/><StatCard title="Click rate" value={`${report.campaigns?.click_rate||0}%`} icon={MousePointerClick}/><StatCard title="Bounced" value={report.campaigns?.bounced||0} icon={AlertCircle}/></div>
    <div className="grid xl:grid-cols-2 gap-6"><Card><CardHeader><CardTitle>Owner performance</CardTitle></CardHeader><CardContent className="space-y-3">{(report.owners||[]).length?(report.owners||[]).map((x:any)=><div key={x.name} className="flex items-center justify-between border-b pb-3"><div><p className="font-medium">{x.name}</p><p className="text-xs text-muted-foreground">{x.leads} assigned leads</p></div><Badge variant="outline">{x.conversions} converted · {x.rate}%</Badge></div>):<p className="text-sm text-muted-foreground">No owner data for this period.</p>}</CardContent></Card><Card><CardHeader><CardTitle>Program interest</CardTitle></CardHeader><CardContent className="space-y-3">{(report.programs||[]).length?(report.programs||[]).map((x:any)=><div key={x.name} className="flex items-center justify-between border-b pb-3"><div><p className="font-medium">{x.name}</p><p className="text-xs text-muted-foreground">{x.leads} interested leads</p></div><Badge variant="outline">{x.conversions} converted</Badge></div>):<p className="text-sm text-muted-foreground">No program-interest data for this period.</p>}</CardContent></Card></div></>}</div>;
}
