// @ts-nocheck
import { useState } from 'react';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { supabase } from '@/lib/supabase';
import { useFeedbackCampaigns } from '@/hooks/useFeedback';
import { FeedbackResults } from '@/components/feedback/FeedbackResults';
import { PageHeader } from '@/components/shared/PageHeader';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Loader2, MessageSquareHeart, Pencil, Plus } from 'lucide-react';
import { toast } from 'sonner';

export default function FeedbackPage() {
  const client = useQueryClient(); const { data: campaigns = [], isLoading } = useFeedbackCampaigns();
  const [results, setResults] = useState<string | null>(null); const [createOpen, setCreateOpen] = useState(false);
  const [form, setForm] = useState({ template_id:'', title:'', classroom_id:'', cohort_id:'', closes_at:'' });
  const { data: setup } = useQuery({ queryKey:['feedback-admin-setup'], queryFn: async () => { const [templates,classrooms,cohorts,cases] = await Promise.all([supabase.from('feedback_templates').select('*,feedback_questions(*)').order('campaign_type'),supabase.from('classrooms').select('id,name').eq('status','active').order('name'),supabase.from('cohorts').select('id,cohort_label,classroom_id').order('start_date',{ascending:false}),supabase.from('feedback_cases').select('*,feedback_responses(campaign_id,student_id)').order('created_at',{ascending:false})]); for (const r of [templates,classrooms,cohorts,cases]) if (r.error) throw r.error; return {templates:templates.data||[],classrooms:classrooms.data||[],cohorts:cohorts.data||[],cases:cases.data||[]}; } });
  const create = async () => { try { const selectedTemplate=setup?.templates.find((x:any)=>x.id===form.template_id); const { error }=await supabase.rpc('create_feedback_campaign',{p_template_id:form.template_id,p_title:form.title,p_classroom_id:form.classroom_id,p_cohort_id:form.cohort_id||null,p_schedule_id:null,p_instructor_id:null,p_opens_at:new Date().toISOString(),p_closes_at:form.closes_at?new Date(form.closes_at).toISOString():new Date(Date.now()+7*86400000).toISOString()}); if(error)throw error; toast.success(`${selectedTemplate?.campaign_type==='course'?'Course':'Session'} feedback launched`);setCreateOpen(false);client.invalidateQueries({queryKey:['feedback-campaigns']}); } catch(e:any){toast.error(e.message);} };
  return <div><PageHeader title="Learner Feedback" description="Manage confidential surveys, review trends, and follow up on concerns." actions={<Button onClick={()=>setCreateOpen(true)}><Plus className="h-4 w-4 mr-2" />Launch survey</Button>} />
    <Tabs defaultValue="campaigns" className="mt-6"><TabsList><TabsTrigger value="campaigns">Campaigns</TabsTrigger><TabsTrigger value="templates">Templates</TabsTrigger><TabsTrigger value="cases">Follow-up cases</TabsTrigger></TabsList>
      <TabsContent value="campaigns" className="mt-4">{isLoading?<Loader2 className="animate-spin"/>:<div className="space-y-3">{campaigns.map((c:any)=><button key={c.id} onClick={()=>setResults(c.id)} className="w-full text-left rounded-xl border p-4 hover:bg-muted/40 flex justify-between gap-3"><div><p className="font-medium">{c.title}</p><p className="text-sm text-muted-foreground mt-1">{c.classrooms?.name}{c.cohorts?.cohort_label?` · ${c.cohorts.cohort_label}`:''} · closes {new Date(c.closes_at).toLocaleDateString('en-NG')}</p></div><div className="flex gap-2"><Badge variant="outline" className="capitalize">{c.campaign_type}</Badge><Badge className="capitalize">{c.status}</Badge></div></button>)}{!campaigns.length&&<p className="text-muted-foreground py-10 text-center">No campaigns yet.</p>}</div>}</TabsContent>
      <TabsContent value="templates" className="mt-4"><div className="grid md:grid-cols-2 gap-4">{setup?.templates.map((t:any)=><div key={t.id} className="rounded-xl border p-5"><div className="flex justify-between"><div><p className="font-semibold">{t.name}</p><p className="text-sm text-muted-foreground mt-1">{t.description}</p></div><Badge variant="outline" className="capitalize h-fit">{t.campaign_type}</Badge></div><p className="text-xs text-muted-foreground mt-4">{t.feedback_questions?.length||0} questions · version {t.version}</p><Button variant="outline" size="sm" className="mt-3" disabled title="Template editing is versioned; duplicate via database migration for this release"><Pencil className="h-3.5 w-3.5 mr-1"/>Versioned template</Button></div>)}</div></TabsContent>
      <TabsContent value="cases" className="mt-4"><div className="space-y-3">{setup?.cases.map((c:any)=><div key={c.id} className="rounded-xl border p-4 flex justify-between"><div><p className="font-medium">{c.title}</p><p className="text-sm text-muted-foreground">Priority: {c.priority}</p></div><Badge className="capitalize">{c.status.replace('_',' ')}</Badge></div>)}{!setup?.cases.length&&<p className="text-muted-foreground py-10 text-center">No flagged feedback cases.</p>}</div></TabsContent>
    </Tabs>
    <Dialog open={!!results} onOpenChange={o=>!o&&setResults(null)}><DialogContent className="max-w-3xl max-h-[90vh] overflow-y-auto"><DialogHeader><DialogTitle>Feedback results</DialogTitle></DialogHeader>{results&&<FeedbackResults campaignId={results}/>}</DialogContent></Dialog>
    <Dialog open={createOpen} onOpenChange={setCreateOpen}><DialogContent><DialogHeader><DialogTitle>Launch feedback survey</DialogTitle></DialogHeader><div className="space-y-4"><div><Label>Template</Label><Select value={form.template_id} onValueChange={v=>setForm({...form,template_id:v})}><SelectTrigger><SelectValue placeholder="Choose template"/></SelectTrigger><SelectContent>{setup?.templates.filter((t:any)=>t.active).map((t:any)=><SelectItem key={t.id} value={t.id}>{t.name}</SelectItem>)}</SelectContent></Select></div><div><Label>Title</Label><Input value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></div><div><Label>Classroom</Label><Select value={form.classroom_id} onValueChange={v=>setForm({...form,classroom_id:v,cohort_id:''})}><SelectTrigger><SelectValue placeholder="Choose classroom"/></SelectTrigger><SelectContent>{setup?.classrooms.map((x:any)=><SelectItem key={x.id} value={x.id}>{x.name}</SelectItem>)}</SelectContent></Select></div><div><Label>Cohort (optional)</Label><Select value={form.cohort_id||'all'} onValueChange={v=>setForm({...form,cohort_id:v==='all'?'':v})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">Entire classroom</SelectItem>{setup?.cohorts.filter((x:any)=>x.classroom_id===form.classroom_id).map((x:any)=><SelectItem key={x.id} value={x.id}>{x.cohort_label}</SelectItem>)}</SelectContent></Select></div><div><Label>Closes</Label><Input type="datetime-local" value={form.closes_at} onChange={e=>setForm({...form,closes_at:e.target.value})}/></div><Button className="w-full" disabled={!form.template_id||!form.title.trim()||!form.classroom_id} onClick={create}>Launch survey</Button></div></DialogContent></Dialog>
  </div>;
}
